name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: main

trigger:
  branches:
    include:
    - release/*
    - main
    - feature/*

pr:
  branches:
    include:
    - main

parameters:
- name: location
  type: string
  displayName: 'Select Deploy location'
  default: westeurope
  values:
    - westeurope
    - northeurope
- name: shaUse
  type: boolean
  displayName: 'Use Self Host agent'
  default: true
- name: cdn 
  type: boolean
  displayName: 'New Version of CDN'
  default: true
- name: tran 
  type: boolean
  displayName: 'Transformation Deployment'
  default: false
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false

variables:
- group: dsi-global
- name: tran
  ${{ if eq(parameters.tran, 'true') }}: 
    value: true
  ${{ else }}:
    value: false
- name: dev
  ${{ if or(eq(parameters.dev, 'true'), contains(variables['Build.SourceBranch'],'feature')) }}:
    value: true
  ${{ else }}:
    value: false
- name: test
  ${{ if or(eq(parameters.test, 'true'), contains(variables['Build.SourceBranch'],'feature')) }}:
    value: true
  ${{ else }}:
    value: false
- name: pp
  ${{ if and(or(eq(parameters.pp, 'true'), contains(variables['Build.SourceBranch'],'main')), not(contains(variables['Build.SourceVersionMessage'],'Upgrade to version'))) }}:
    value: true
  ${{ else }}:
    value: false
- name: pr
  ${{ if or(eq(parameters.pr, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false
- name: applicationFullName
  value: 'ui-toolkit'    

stages:

# Code Scans & Build the artifact for deployment
- stage: scanApp
  displayName: "Scan tools & Build"
  jobs:
  # Code scaning tools
  - template:  pipeline/scanTools.yml@devopsTemplates
    parameters:
      npmInstCmd: 'install --force --json --no-package-lock'
      AppDeploy: true

- ${{ each var in variables }}:
  - ${{ if in(var.key, 'tran','dev','test','pp','pr') }}:
    - ${{ if eq(var.value, 'true') }}:
      - stage: Deployment_${{var.Key}}
        dependsOn: 
        - scanApp
        variables:
        - name: environmentId
          ${{ if eq(var.key, 'tran') }}:
            value: d03
          ${{ if eq(var.key, 'dev') }}:
            value: d01
          ${{ if eq(var.key, 'test') }}:
            value: t01
          ${{ if eq(var.key, 'pp') }}:
            value: t02
          ${{ if eq(var.key, 'pr') }}:
            value: p01
        - name: neuProjectId
          ${{ if eq(parameters.location, 'westeurope') }}:
            value: ""
          ${{ else }}:
            value: "neu-"
        - name: SubShortName
          value: $(platformGlobalIdentifier)$(environmentId)
        - name: storageAccountName
          ${{ if eq(parameters.location, 'westeurope') }}:
            value: $(SubShortName)signinshdstr
          ${{ else }}:
            value: $(SubShortName)neusigninshdstr          
        - name: ShdResourceGroupName
          value: $(SubShortName)-$(neuProjectId)shd
        - name: UIContainerName
          value: ui-assets
        - name: azureCdnName
          value: $(SubShortName)-signin-shd-cdn
        - name: cdnEndpointName
          value: $(SubShortName)-signin-shd-cdnep
        - name: keyVaultName
          value: $(SubShortName)-signin-kv
        displayName: "Deployment [${{var.Key}}] ${{parameters.location}}"
        ${{ if eq(parameters.shaUse, 'true') }}:
          ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
            pool: Self-hosted Dev
          ${{ elseif eq(var.key, 'pr') }}:
            pool: Self-hosted Prod
          ${{ else }}:
            pool: Self-hosted Test
        jobs:
        - deployment: 'Deploy_${{var.Key}}'
          displayName: Updated content of CDN
          environment: ${{var.Key}}
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self
                    persistCredentials: true
                  - checkout: devopsTemplates

                  - task: AzureCLI@2
                    displayName: 'White-list keyVault'
                    condition: ${{not(parameters.shaUse)}}
                    inputs:
                      ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                        azureSubscription: $(devServiceConnection)
                      ${{ elseif eq(var.key, 'pr') }}:
                        azureSubscription: $(prodServiceConnection)
                      ${{ else }}:
                        azureSubscription: $(testServiceConnection)
                      scriptType: 'pscore'
                      scriptLocation: 'scriptPath'
                      scriptPath: 'login.dfe.devops/scripts/keyvaultWhiteListCheck.ps1'
                      arguments: '-keyVault $(keyVaultName) -keyVaultRg $(keyVaultResourceGroupName) -WhiteListIP $True -NotSelfHost $True'
                      workingDirectory: $(System.DefaultWorkingDirectory)

                  - task: AzureCLI@2
                    displayName: 'Enable Access to Storage Account'
                    condition: ${{not(parameters.shaUse)}}
                    inputs:
                      ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                        azureSubscription: $(devServiceConnection)
                      ${{ elseif eq(var.key, 'pr') }}:
                        azureSubscription: $(prodServiceConnection)
                      ${{ else }}:
                        azureSubscription: $(testServiceConnection)
                      scriptType: pscore
                      scriptLocation: inlineScript
                      inlineScript: |
                        $publicIp = Invoke-RestMethod -uri https://api.ipify.org
                        Write-Host "Public Ip : $publicIp "
                        az storage account network-rule add --ip-address $publicIp --resource-group $(ShdResourceGroupName) --account-name $(storageAccountName)
                        Write-Host "##vso[task.setvariable variable=agentIp]$publicIp"

                  - task: AzureCLI@2
                    displayName: 'Empty, upload & Purge Storage & CDN Contents & Updated CDN Version  '
                    env:
                      newCdnV: ${{ parameters.cdn }}
                    inputs:
                      ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                        azureSubscription: $(devServiceConnection)
                      ${{ elseif eq(var.key, 'pr') }}:
                        azureSubscription: $(prodServiceConnection)
                      ${{ else }}:
                        azureSubscription: $(testServiceConnection)
                      scriptType: pscore
                      scriptLocation: inlineScript
                      ${{ if not(parameters.shaUse) }}:
                        workingDirectory: $(System.DefaultWorkingDirectory)/login.dfe.ui-toolkit
                      inlineScript: |
                        $ErrorActionPreference = "Stop"
                        write-output "Waiting for FW rule to apply." 

                        $FWTestAttempt = 1
                        $FWTestMax = 25
                        Start-Sleep -Seconds 35
                        do {
                            try {
                                az storage blob delete-batch --account-name $(storageAccountName) --source $(UIContainerName) --only-show-errors --auth-mode=login
                                if ($? -eq $false) {
                                  throw 'Failed to  delete-batch on storage account'
                                }
                                az storage blob upload-batch  --account-name $(storageAccountName) --source  $(System.DefaultWorkingDirectory)/dist --destination $(UIContainerName) --auth-mode=login
                                if ($? -eq $false) {
                                  throw 'Failed to  upload-batch on storage account'
                                }

                                $FWTest = $true
                                write-output "Storage is now accessible & and data is uploaded"
                                
                                if($ShdResourceGroupName -NotLike '*neu*'){
                                  az cdn endpoint purge --content-paths /* --profile-name $(azureCdnName) -g $(ShdResourceGroupName) -n $(cdnEndpointName) 

                                  if($env:newCdnV){
                                    $cdnAssetsVersion = $(az keyvault secret show -n cdnAssetsVersion --vault-name $(keyVaultName)).value
                                    $cdnAssetsVersion = [decimal]$cdnAssetsVersion
                                    $newCdnAssetsVersion = $cdnAssetsVersion+0.1
                                    az keyvault secret set --name cdnAssetsVersion --vault-name $(keyVaultName) --value $newCdnAssetsVersion
                                  }
                                }

                                exit 0
                            }
                            catch {
                                if ($FWTestAttempt -lt $FWTestMax) {
                                    write-output "Unable to access storage account $FWTestAttempt/$FWTestMax. Waiting for FW rule to take effect."
                                    $FWTestAttempt++
                                    Start-Sleep -Seconds 20
                                }
                                else {
                                    Write-Error "Unable to access storage account $FWTestAttempt/$FWTestMax."
                                }
                            }
                        } while ($FWTestAttempt -lt $FWTestMax)

                  - task: AzureCLI@2
                    displayName: Remove White-list of storage
                    condition: ${{not(parameters.shaUse)}}
                    inputs:
                      ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                        azureSubscription: $(devServiceConnection)
                      ${{ elseif eq(var.key, 'pr') }}:
                        azureSubscription: $(prodServiceConnection)
                      ${{ else }}:
                        azureSubscription: $(testServiceConnection)
                      scriptType: pscore
                      scriptLocation: inlineScript
                      inlineScript: |
                        az storage account network-rule remove -g $(ShdResourceGroupName) --account-name $(storageAccountName) --ip-address $(agentIp)

                  - task: AzureCLI@2
                    displayName: 'Remove White-list keyVault'
                    condition:  ${{not(parameters.shaUse)}}
                    inputs:
                      ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                        azureSubscription: $(devServiceConnection)
                      ${{ elseif eq(var.key, 'pr') }}:
                        azureSubscription: $(prodServiceConnection)
                      ${{ else }}:
                        azureSubscription: $(testServiceConnection)
                      scriptType: 'pscore'
                      scriptLocation: 'scriptPath'
                      scriptPath: 'login.dfe.devops/scripts/keyvaultWhiteListCheck.ps1'
                      arguments: '-keyVault $(keyVaultName) -keyVaultRg $(keyVaultResourceGroupName) -WhiteListIP $False -NotSelfHost $True'
                      workingDirectory: $(System.DefaultWorkingDirectory)
                  
                  - task: PowerShell@2
                    displayName: 'Release Branch Creation'
                    condition: and(contains(variables['Build.SourceBranch'],'main'),eq('${{parameters.location}}', 'westeurope'))
                    inputs:
                      targetType: 'inline'
                      workingDirectory: $(Build.Repository.LocalPath)/${{variables.applicationRepoName}}
                      script: |              
                        git config --global user.email "pipeline@example.com"
                        git config --global user.name "Azure Devops Pipeline"
                        
                        $version = $(node -p "require('./package.json').version")
                        npm version major -m "Upgrade to version %s"
                        $newVersion = $(node -p "require('./package.json').version")
                        write-output "package.json Version Current: $version"
                        write-output "package.json Version New: $newVersion"

                        $branch = "release/$newVersion"
                        git push origin --delete $branch  
                        git checkout -b $branch

                        git add *
                        git push origin HEAD:$branch

      - ${{ if and(eq(var.key, 'pr'),eq(parameters.location, 'westeurope')) }}:
        - stage: branchPrTag
          displayName: "GitHub PR & Release Branch Tag"
          dependsOn: 
          - Deployment_${{var.Key}}
          jobs:
          - template:  pipeline/tagCreation.yml@devopsTemplates
            parameters:
              applicationName: ${{variables.applicationFullName}}      

